title: dyf's blog
description: >- 
    "一只猫～"
baseurl: ""
url: "http://blog.dyf.ink" # http://example.com
pictures: /_pictures/

repository: Explainaur/explainaur.github.io

# Build settings
theme: portfolyou-jekyll-theme
plugins:
  - jekyll-feed
  - jemoji

nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : dyf
  image             : https://github.com/Explainaur/hexo-blog/blob/master/source/pictures/cat.png?raw=true
  email             : dyf.auroa@gmail.com
  github            : Explainaur
# gitlab            : your_username
  stackoverflow     : Explainaur
  twitter           : YIFAN DONG

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude: [vendor]

# exclude:
  # - README.md
  # - CONTRIBUTING.md
  # - LICENSE
  # - "*.log"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
